"""json media in post

Revision ID: 5e5c7901baca
Revises: b814ee8e1af6
Create Date: 2019-11-17 14:53:32.596032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5c7901baca'
down_revision = 'b814ee8e1af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('media', sa.String(length=1036), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'media')
    # ### end Alembic commands ###
